# Generated by Django 5.2.3 on 2025-06-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0003_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('matchdate', models.DateField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
